### ISSUE TITLE
NullPointerException at spotbugs annotation

### ISSUE THREAD

**Issue by seito2** [T45K/Bitbucket-Server-Code-Insights-plugin#192]
The format of the spotbugs may not be considered.

Currently the code parse `BugInstance` -> `SourceLine`, but sometime spotbug will generate `BugInstance` ->  `Field` -> `SourceLine`.

## Error log
```
java.lang.NullPointerException
	at io.jenkins.plugins.codeInsights.domain.SpotBugsAnnotationProvider.convert(SpotBugsAnnotationProvider.kt:21)
	at io.jenkins.plugins.codeInsights.usecase.AnnotationUsecase.execute(AnnotationUsecase.kt:36)
	at io.jenkins.plugins.codeInsights.KotlinEntryPoint.delegate(KotlinEntryPoint.kt:68)
	at io.jenkins.plugins.codeInsights.CodeInsightsBuilder.perform(CodeInsightsBuilder.java:76)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by T45K** [comment]
thank you for reporting

**Comment by T45K** [comment]
Yes, you're right.
I checked xml you gave, and realized some `SourceLine` tag right under `BugInstance` doesn't have start line information, but ones right under `Class`, `Type`, etc. have it instead.
I'll modify the source code to check those tags when one right under `BugInstance` doesn't have the info.

**Comment by T45K** [comment]
I changed my mind.
I guess just SpotBugs found what is bad but couldn't find where is bad.
In this case, it is better to show the error massage on the top position of file in PR view

**Comment by seito2** [comment]
Ah, I got it.
Thank you 😌
