### ISSUE TITLE
masterブランチを解決できない

### ISSUE THREAD

**Issue by T45K** [T45K/Bitbucket-Server-Code-Insights-plugin#21]
```
java.lang.NullPointerException: git.repository.resolve(base) must not be null
	at io.jenkins.plugins.codeInsights.domain.GitRepo.detectChangedFiles(GitRepo.kt:29)
	at io.jenkins.plugins.codeInsights.KotlinEntryPoint.delegate(KotlinEntryPoint.kt:40)
	at io.jenkins.plugins.codeInsights.CodeInsightsBuilder.perform(CodeInsightsBuilder.java:59)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
```
何？

**Comment by T45K** [comment]
headの解析はできてる

**Comment by T45K** [comment]
`remotes/origin/master`でやる？
